spring:
  datasource:
    url: jdbc:h2:mem:bank;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true


jwt:
  public:
    key: classpath:rsa.public.key
  private:
    key: classpath:rsa.private.key

springdoc:
  api-docs:
    path: /rest-api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui
